version: "2.2"

services:
  traefik:
    image: traefik:v2.3.6
    restart: always
    container_name: traefik
    networks:
      - proxy
    ports:
      - "80:80"
      - "8081:8080" # traefik dashboard
      - "443:443"
      - "10000:10000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.yml:/etc/traefik/traefik.yml:ro

      - traefik_log:/var/log/traefik/
    environment:
      - "TZ=Europe/Paris"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.yourdomain.com`)"
      - "traefik.http.routers.api.service=api@internal" # Let the dashboard access the traefik api     

networks:
  proxy:
    external: true

volumes:
  traefik_log: